# Generated by Django 5.1.6 on 2025-02-19 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Категории видов спорта',
                'verbose_name_plural': 'Категории видов спорта',
            },
        ),
        migrations.CreateModel(
            name='Directors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Руководитель клуба',
                'verbose_name_plural': 'Руководители клубов',
            },
        ),
        migrations.CreateModel(
            name='Clubs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Клуб ветеранов спорта')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Год основания')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес клуба')),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sport.directors', verbose_name='Руководитель клуба')),
            ],
            options={
                'verbose_name': 'Клуб ветеранов спорта',
                'verbose_name_plural': 'Клубы ветеранов спорта',
            },
        ),
        migrations.CreateModel(
            name='SportTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название спорта')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sport.category', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Виды спорта',
                'verbose_name_plural': 'Виды спорта',
            },
        ),
        migrations.CreateModel(
            name='Veterans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('gender', models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=100, verbose_name='Пол')),
                ('age_group', models.CharField(max_length=100, verbose_name='Возрастная группа')),
                ('photo', models.ImageField(upload_to='veterans_photos', verbose_name='Фото ветерана')),
                ('achievements', models.CharField(blank=True, max_length=100, verbose_name='Перечень наград')),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sport.clubs', verbose_name='Клуб ветеранов спорта')),
                ('sport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sport.sporttypes', verbose_name='Вид спорта')),
            ],
            options={
                'verbose_name': 'Ветерана',
                'verbose_name_plural': 'Ветераны',
            },
        ),
    ]
