# Generated by Django 5.1.6 on 2025-02-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubs',
            name='time_create',
            field=models.DateField(auto_now_add=True, verbose_name='Год основания'),
        ),
    ]
