# Generated by Django 5.1.6 on 2025-02-25 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0002_alter_clubs_time_create'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubs',
            name='director',
        ),
        migrations.DeleteModel(
            name='Directors',
        ),
    ]
