# Generated by Django 5.1.6 on 2025-02-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0003_remove_clubs_director_delete_directors'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubs',
            name='director',
            field=models.CharField(blank=True, max_length=100, verbose_name='Руководитель клуба'),
        ),
    ]
