# Generated by Django 5.1.6 on 2025-02-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0004_clubs_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubs',
            name='director',
            field=models.CharField(max_length=100, verbose_name='Руководитель клуба'),
        ),
    ]
