# Generated by Django 5.1.6 on 2025-02-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0010_alter_veterans_achievements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veterans',
            name='achievements',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Перечень наград'),
        ),
    ]
